services:
  mc:
    image: itzg/minecraft-server
    tty: true
    init: true
    restart: unless-stopped
    container_name: minecraft-server-pixelmon
    cpus: 3
    mem_limit: 4400m
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE" # MODPACK_PLATFORM: AUTO_CURSEFORGE
      # MODPACK_PLATFORM: AUTO_MODRINTH
      TYPE: FABRIC
      # Allocate API key from https://console.curseforge.com/
      # and set in .env file making sure to double up dollar signs, such as
      # CF_API_KEY=$$2a$$10$$....
      # Refer to https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key
      # CF_API_KEY: ${CF_API_KEY:?}
      # CF_SLUG: the-pixelmon-modpack
      # CF_SLUG: pixelmon
      # CF_FILENAME_MATCHER: "9.2.10"
      USE_PLUGINS: true
      MODRINTH_PROJECTS: |
        fabric-api
        cobblemon
      MEMORY: 4G
      VERSION: 1.21.1
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./storage/minecraft-server:/data
