# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.secret_scanning_location_discussion_comment import SecretScanningLocationDiscussionComment

class TestSecretScanningLocationDiscussionComment(unittest.TestCase):
    """SecretScanningLocationDiscussionComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretScanningLocationDiscussionComment:
        """Test SecretScanningLocationDiscussionComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretScanningLocationDiscussionComment`
        """
        model = SecretScanningLocationDiscussionComment()
        if include_optional:
            return SecretScanningLocationDiscussionComment(
                discussion_comment_url = 'https://github.com/community/community/discussions/39082#discussioncomment-4158232'
            )
        else:
            return SecretScanningLocationDiscussionComment(
                discussion_comment_url = 'https://github.com/community/community/discussions/39082#discussioncomment-4158232',
        )
        """

    def testSecretScanningLocationDiscussionComment(self):
        """Test SecretScanningLocationDiscussionComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
