# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.deployment1_payload import Deployment1Payload

class TestDeployment1Payload(unittest.TestCase):
    """Deployment1Payload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Deployment1Payload:
        """Test Deployment1Payload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Deployment1Payload`
        """
        model = Deployment1Payload()
        if include_optional:
            return Deployment1Payload(
            )
        else:
            return Deployment1Payload(
        )
        """

    def testDeployment1Payload(self):
        """Test Deployment1Payload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
