# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.environment_approvals_environments_inner import EnvironmentApprovalsEnvironmentsInner

class TestEnvironmentApprovalsEnvironmentsInner(unittest.TestCase):
    """EnvironmentApprovalsEnvironmentsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnvironmentApprovalsEnvironmentsInner:
        """Test EnvironmentApprovalsEnvironmentsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnvironmentApprovalsEnvironmentsInner`
        """
        model = EnvironmentApprovalsEnvironmentsInner()
        if include_optional:
            return EnvironmentApprovalsEnvironmentsInner(
                id = 56780428,
                node_id = 'MDExOkVudmlyb25tZW50NTY3ODA0Mjg=',
                name = 'staging',
                url = 'https://api.github.com/repos/github/hello-world/environments/staging',
                html_url = 'https://github.com/github/hello-world/deployments/activity_log?environments_filter=staging',
                created_at = '2020-11-23T22:00:40Z',
                updated_at = '2020-11-23T22:00:40Z'
            )
        else:
            return EnvironmentApprovalsEnvironmentsInner(
        )
        """

    def testEnvironmentApprovalsEnvironmentsInner(self):
        """Test EnvironmentApprovalsEnvironmentsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
