# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.actions_list_org_variables200_response import ActionsListOrgVariables200Response

class TestActionsListOrgVariables200Response(unittest.TestCase):
    """ActionsListOrgVariables200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionsListOrgVariables200Response:
        """Test ActionsListOrgVariables200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionsListOrgVariables200Response`
        """
        model = ActionsListOrgVariables200Response()
        if include_optional:
            return ActionsListOrgVariables200Response(
                total_count = 56,
                variables = [
                    github_openapi.models.actions_variable_for_an_organization.Actions Variable for an Organization(
                        name = 'USERNAME', 
                        value = 'octocat', 
                        created_at = '2019-01-24T22:45:36Z', 
                        updated_at = '2019-01-24T22:45:36Z', 
                        visibility = 'all', 
                        selected_repositories_url = 'https://api.github.com/organizations/org/variables/USERNAME/repositories', )
                    ]
            )
        else:
            return ActionsListOrgVariables200Response(
                total_count = 56,
                variables = [
                    github_openapi.models.actions_variable_for_an_organization.Actions Variable for an Organization(
                        name = 'USERNAME', 
                        value = 'octocat', 
                        created_at = '2019-01-24T22:45:36Z', 
                        updated_at = '2019-01-24T22:45:36Z', 
                        visibility = 'all', 
                        selected_repositories_url = 'https://api.github.com/organizations/org/variables/USERNAME/repositories', )
                    ],
        )
        """

    def testActionsListOrgVariables200Response(self):
        """Test ActionsListOrgVariables200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
