# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.webhooks_team import WebhooksTeam

class TestWebhooksTeam(unittest.TestCase):
    """WebhooksTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhooksTeam:
        """Test WebhooksTeam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhooksTeam`
        """
        model = WebhooksTeam()
        if include_optional:
            return WebhooksTeam(
                deleted = True,
                description = '',
                html_url = '',
                id = 56,
                members_url = '',
                name = '',
                node_id = '',
                parent = github_openapi.models.webhooks_team_parent.webhooks_team_parent(
                    description = '', 
                    html_url = '', 
                    id = 56, 
                    members_url = '', 
                    name = '', 
                    node_id = '', 
                    permission = '', 
                    privacy = 'open', 
                    notification_setting = 'notifications_enabled', 
                    repositories_url = '', 
                    slug = '', 
                    url = '', ),
                permission = '',
                privacy = 'open',
                notification_setting = 'notifications_enabled',
                repositories_url = '',
                slug = '',
                url = ''
            )
        else:
            return WebhooksTeam(
                id = 56,
                name = '',
        )
        """

    def testWebhooksTeam(self):
        """Test WebhooksTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
