# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.repos_create_or_update_file_contents_request import ReposCreateOrUpdateFileContentsRequest

class TestReposCreateOrUpdateFileContentsRequest(unittest.TestCase):
    """ReposCreateOrUpdateFileContentsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReposCreateOrUpdateFileContentsRequest:
        """Test ReposCreateOrUpdateFileContentsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReposCreateOrUpdateFileContentsRequest`
        """
        model = ReposCreateOrUpdateFileContentsRequest()
        if include_optional:
            return ReposCreateOrUpdateFileContentsRequest(
                message = '',
                content = '',
                sha = '',
                branch = '',
                committer = github_openapi.models.repos_create_or_update_file_contents_request_committer.repos_create_or_update_file_contents_request_committer(
                    name = '', 
                    email = '', 
                    date = '"2013-01-05T13:13:22+05:00"', ),
                author = github_openapi.models.repos_create_or_update_file_contents_request_author.repos_create_or_update_file_contents_request_author(
                    name = '', 
                    email = '', 
                    date = '"2013-01-15T17:13:22+05:00"', )
            )
        else:
            return ReposCreateOrUpdateFileContentsRequest(
                message = '',
                content = '',
        )
        """

    def testReposCreateOrUpdateFileContentsRequest(self):
        """Test ReposCreateOrUpdateFileContentsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
