# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.codespaces_list_devcontainers_in_repository_for_authenticated_user200_response_devcontainers_inner import CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner

class TestCodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner(unittest.TestCase):
    """CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner:
        """Test CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner`
        """
        model = CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner()
        if include_optional:
            return CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner(
                path = '',
                name = '',
                display_name = ''
            )
        else:
            return CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner(
                path = '',
        )
        """

    def testCodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner(self):
        """Test CodespacesListDevcontainersInRepositoryForAuthenticatedUser200ResponseDevcontainersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
