# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.issues_set_labels_request_one_of1 import IssuesSetLabelsRequestOneOf1

class TestIssuesSetLabelsRequestOneOf1(unittest.TestCase):
    """IssuesSetLabelsRequestOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssuesSetLabelsRequestOneOf1:
        """Test IssuesSetLabelsRequestOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssuesSetLabelsRequestOneOf1`
        """
        model = IssuesSetLabelsRequestOneOf1()
        if include_optional:
            return IssuesSetLabelsRequestOneOf1(
                labels = [
                    github_openapi.models.issues_set_labels_request_one_of_1_labels_inner.issues_set_labels_request_oneOf_1_labels_inner(
                        name = '', )
                    ]
            )
        else:
            return IssuesSetLabelsRequestOneOf1(
        )
        """

    def testIssuesSetLabelsRequestOneOf1(self):
        """Test IssuesSetLabelsRequestOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
