# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.repository_webhooks_template_repository_owner import RepositoryWebhooksTemplateRepositoryOwner

class TestRepositoryWebhooksTemplateRepositoryOwner(unittest.TestCase):
    """RepositoryWebhooksTemplateRepositoryOwner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepositoryWebhooksTemplateRepositoryOwner:
        """Test RepositoryWebhooksTemplateRepositoryOwner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepositoryWebhooksTemplateRepositoryOwner`
        """
        model = RepositoryWebhooksTemplateRepositoryOwner()
        if include_optional:
            return RepositoryWebhooksTemplateRepositoryOwner(
                login = '',
                id = 56,
                node_id = '',
                avatar_url = '',
                gravatar_id = '',
                url = '',
                html_url = '',
                followers_url = '',
                following_url = '',
                gists_url = '',
                starred_url = '',
                subscriptions_url = '',
                organizations_url = '',
                repos_url = '',
                events_url = '',
                received_events_url = '',
                type = '',
                site_admin = True
            )
        else:
            return RepositoryWebhooksTemplateRepositoryOwner(
        )
        """

    def testRepositoryWebhooksTemplateRepositoryOwner(self):
        """Test RepositoryWebhooksTemplateRepositoryOwner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
