# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.issues_update_milestone_request import IssuesUpdateMilestoneRequest

class TestIssuesUpdateMilestoneRequest(unittest.TestCase):
    """IssuesUpdateMilestoneRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IssuesUpdateMilestoneRequest:
        """Test IssuesUpdateMilestoneRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IssuesUpdateMilestoneRequest`
        """
        model = IssuesUpdateMilestoneRequest()
        if include_optional:
            return IssuesUpdateMilestoneRequest(
                title = '',
                state = 'open',
                description = '',
                due_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return IssuesUpdateMilestoneRequest(
        )
        """

    def testIssuesUpdateMilestoneRequest(self):
        """Test IssuesUpdateMilestoneRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
