# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.pull_request_review_comment_links import PullRequestReviewCommentLinks

class TestPullRequestReviewCommentLinks(unittest.TestCase):
    """PullRequestReviewCommentLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PullRequestReviewCommentLinks:
        """Test PullRequestReviewCommentLinks
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PullRequestReviewCommentLinks`
        """
        model = PullRequestReviewCommentLinks()
        if include_optional:
            return PullRequestReviewCommentLinks(
                var_self = github_openapi.models.pull_request_review_comment__links_self.pull_request_review_comment__links_self(
                    href = 'https://api.github.com/repos/octocat/Hello-World/pulls/comments/1', ),
                html = github_openapi.models.pull_request_review_comment__links_html.pull_request_review_comment__links_html(
                    href = 'https://github.com/octocat/Hello-World/pull/1#discussion-diff-1', ),
                pull_request = github_openapi.models.pull_request_review_comment__links_pull_request.pull_request_review_comment__links_pull_request(
                    href = 'https://api.github.com/repos/octocat/Hello-World/pulls/1', )
            )
        else:
            return PullRequestReviewCommentLinks(
                var_self = github_openapi.models.pull_request_review_comment__links_self.pull_request_review_comment__links_self(
                    href = 'https://api.github.com/repos/octocat/Hello-World/pulls/comments/1', ),
                html = github_openapi.models.pull_request_review_comment__links_html.pull_request_review_comment__links_html(
                    href = 'https://github.com/octocat/Hello-World/pull/1#discussion-diff-1', ),
                pull_request = github_openapi.models.pull_request_review_comment__links_pull_request.pull_request_review_comment__links_pull_request(
                    href = 'https://api.github.com/repos/octocat/Hello-World/pulls/1', ),
        )
        """

    def testPullRequestReviewCommentLinks(self):
        """Test PullRequestReviewCommentLinks"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
