# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.validation_error_errors_inner_value import ValidationErrorErrorsInnerValue

class TestValidationErrorErrorsInnerValue(unittest.TestCase):
    """ValidationErrorErrorsInnerValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidationErrorErrorsInnerValue:
        """Test ValidationErrorErrorsInnerValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidationErrorErrorsInnerValue`
        """
        model = ValidationErrorErrorsInnerValue()
        if include_optional:
            return ValidationErrorErrorsInnerValue(
            )
        else:
            return ValidationErrorErrorsInnerValue(
        )
        """

    def testValidationErrorErrorsInnerValue(self):
        """Test ValidationErrorErrorsInnerValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
