# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.webhook_discussion_category_changed_changes import WebhookDiscussionCategoryChangedChanges

class TestWebhookDiscussionCategoryChangedChanges(unittest.TestCase):
    """WebhookDiscussionCategoryChangedChanges unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDiscussionCategoryChangedChanges:
        """Test WebhookDiscussionCategoryChangedChanges
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDiscussionCategoryChangedChanges`
        """
        model = WebhookDiscussionCategoryChangedChanges()
        if include_optional:
            return WebhookDiscussionCategoryChangedChanges(
                category = github_openapi.models.webhook_discussion_category_changed_changes_category.webhook_discussion_category_changed_changes_category(
                    from = github_openapi.models.discussion_category.discussion_category(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        emoji = '', 
                        id = 56, 
                        is_answerable = True, 
                        name = '', 
                        node_id = '', 
                        repository_id = 56, 
                        slug = '', 
                        updated_at = '', ), )
            )
        else:
            return WebhookDiscussionCategoryChangedChanges(
                category = github_openapi.models.webhook_discussion_category_changed_changes_category.webhook_discussion_category_changed_changes_category(
                    from = github_openapi.models.discussion_category.discussion_category(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        description = '', 
                        emoji = '', 
                        id = 56, 
                        is_answerable = True, 
                        name = '', 
                        node_id = '', 
                        repository_id = 56, 
                        slug = '', 
                        updated_at = '', ), ),
        )
        """

    def testWebhookDiscussionCategoryChangedChanges(self):
        """Test WebhookDiscussionCategoryChangedChanges"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
