# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.secret_scanning_location_pull_request_review_comment import SecretScanningLocationPullRequestReviewComment

class TestSecretScanningLocationPullRequestReviewComment(unittest.TestCase):
    """SecretScanningLocationPullRequestReviewComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretScanningLocationPullRequestReviewComment:
        """Test SecretScanningLocationPullRequestReviewComment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretScanningLocationPullRequestReviewComment`
        """
        model = SecretScanningLocationPullRequestReviewComment()
        if include_optional:
            return SecretScanningLocationPullRequestReviewComment(
                pull_request_review_comment_url = 'https://api.github.com/repos/octocat/Hello-World/pulls/comments/12'
            )
        else:
            return SecretScanningLocationPullRequestReviewComment(
                pull_request_review_comment_url = 'https://api.github.com/repos/octocat/Hello-World/pulls/comments/12',
        )
        """

    def testSecretScanningLocationPullRequestReviewComment(self):
        """Test SecretScanningLocationPullRequestReviewComment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
