# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.actions_list_repo_organization_variables200_response import ActionsListRepoOrganizationVariables200Response

class TestActionsListRepoOrganizationVariables200Response(unittest.TestCase):
    """ActionsListRepoOrganizationVariables200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionsListRepoOrganizationVariables200Response:
        """Test ActionsListRepoOrganizationVariables200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionsListRepoOrganizationVariables200Response`
        """
        model = ActionsListRepoOrganizationVariables200Response()
        if include_optional:
            return ActionsListRepoOrganizationVariables200Response(
                total_count = 56,
                variables = [
                    github_openapi.models.actions_variable.Actions Variable(
                        name = 'USERNAME', 
                        value = 'octocat', 
                        created_at = '2019-01-24T22:45:36Z', 
                        updated_at = '2019-01-24T22:45:36Z', )
                    ]
            )
        else:
            return ActionsListRepoOrganizationVariables200Response(
                total_count = 56,
                variables = [
                    github_openapi.models.actions_variable.Actions Variable(
                        name = 'USERNAME', 
                        value = 'octocat', 
                        created_at = '2019-01-24T22:45:36Z', 
                        updated_at = '2019-01-24T22:45:36Z', )
                    ],
        )
        """

    def testActionsListRepoOrganizationVariables200Response(self):
        """Test ActionsListRepoOrganizationVariables200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
