# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.webhook_meta_deleted_hook import WebhookMetaDeletedHook

class TestWebhookMetaDeletedHook(unittest.TestCase):
    """WebhookMetaDeletedHook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookMetaDeletedHook:
        """Test WebhookMetaDeletedHook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookMetaDeletedHook`
        """
        model = WebhookMetaDeletedHook()
        if include_optional:
            return WebhookMetaDeletedHook(
                active = True,
                config = github_openapi.models.webhook_meta_deleted_hook_config.webhook_meta_deleted_hook_config(
                    content_type = 'json', 
                    insecure_ssl = '', 
                    secret = '', 
                    url = '', ),
                created_at = '',
                events = [
                    '*'
                    ],
                id = 56,
                name = '',
                type = '',
                updated_at = ''
            )
        else:
            return WebhookMetaDeletedHook(
                active = True,
                config = github_openapi.models.webhook_meta_deleted_hook_config.webhook_meta_deleted_hook_config(
                    content_type = 'json', 
                    insecure_ssl = '', 
                    secret = '', 
                    url = '', ),
                created_at = '',
                events = [
                    '*'
                    ],
                id = 56,
                name = '',
                type = '',
                updated_at = '',
        )
        """

    def testWebhookMetaDeletedHook(self):
        """Test WebhookMetaDeletedHook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
