# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.api.git_api import GitApi


class TestGitApi(unittest.TestCase):
    """GitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GitApi()

    def tearDown(self) -> None:
        pass

    def test_git_create_blob(self) -> None:
        """Test case for git_create_blob

        Create a blob
        """
        pass

    def test_git_create_commit(self) -> None:
        """Test case for git_create_commit

        Create a commit
        """
        pass

    def test_git_create_ref(self) -> None:
        """Test case for git_create_ref

        Create a reference
        """
        pass

    def test_git_create_tag(self) -> None:
        """Test case for git_create_tag

        Create a tag object
        """
        pass

    def test_git_create_tree(self) -> None:
        """Test case for git_create_tree

        Create a tree
        """
        pass

    def test_git_delete_ref(self) -> None:
        """Test case for git_delete_ref

        Delete a reference
        """
        pass

    def test_git_get_blob(self) -> None:
        """Test case for git_get_blob

        Get a blob
        """
        pass

    def test_git_get_commit(self) -> None:
        """Test case for git_get_commit

        Get a commit object
        """
        pass

    def test_git_get_ref(self) -> None:
        """Test case for git_get_ref

        Get a reference
        """
        pass

    def test_git_get_tag(self) -> None:
        """Test case for git_get_tag

        Get a tag
        """
        pass

    def test_git_get_tree(self) -> None:
        """Test case for git_get_tree

        Get a tree
        """
        pass

    def test_git_list_matching_refs(self) -> None:
        """Test case for git_list_matching_refs

        List matching references
        """
        pass

    def test_git_update_ref(self) -> None:
        """Test case for git_update_ref

        Update a reference
        """
        pass


if __name__ == '__main__':
    unittest.main()
