# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.api.code_security_api import CodeSecurityApi


class TestCodeSecurityApi(unittest.TestCase):
    """CodeSecurityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CodeSecurityApi()

    def tearDown(self) -> None:
        pass

    def test_code_security_attach_configuration(self) -> None:
        """Test case for code_security_attach_configuration

        Attach a configuration to repositories
        """
        pass

    def test_code_security_attach_enterprise_configuration(self) -> None:
        """Test case for code_security_attach_enterprise_configuration

        Attach an enterprise configuration to repositories
        """
        pass

    def test_code_security_create_configuration(self) -> None:
        """Test case for code_security_create_configuration

        Create a code security configuration
        """
        pass

    def test_code_security_create_configuration_for_enterprise(self) -> None:
        """Test case for code_security_create_configuration_for_enterprise

        Create a code security configuration for an enterprise
        """
        pass

    def test_code_security_delete_configuration(self) -> None:
        """Test case for code_security_delete_configuration

        Delete a code security configuration
        """
        pass

    def test_code_security_delete_configuration_for_enterprise(self) -> None:
        """Test case for code_security_delete_configuration_for_enterprise

        Delete a code security configuration for an enterprise
        """
        pass

    def test_code_security_detach_configuration(self) -> None:
        """Test case for code_security_detach_configuration

        Detach configurations from repositories
        """
        pass

    def test_code_security_get_configuration(self) -> None:
        """Test case for code_security_get_configuration

        Get a code security configuration
        """
        pass

    def test_code_security_get_configuration_for_repository(self) -> None:
        """Test case for code_security_get_configuration_for_repository

        Get the code security configuration associated with a repository
        """
        pass

    def test_code_security_get_configurations_for_enterprise(self) -> None:
        """Test case for code_security_get_configurations_for_enterprise

        Get code security configurations for an enterprise
        """
        pass

    def test_code_security_get_configurations_for_org(self) -> None:
        """Test case for code_security_get_configurations_for_org

        Get code security configurations for an organization
        """
        pass

    def test_code_security_get_default_configurations(self) -> None:
        """Test case for code_security_get_default_configurations

        Get default code security configurations
        """
        pass

    def test_code_security_get_default_configurations_for_enterprise(self) -> None:
        """Test case for code_security_get_default_configurations_for_enterprise

        Get default code security configurations for an enterprise
        """
        pass

    def test_code_security_get_repositories_for_configuration(self) -> None:
        """Test case for code_security_get_repositories_for_configuration

        Get repositories associated with a code security configuration
        """
        pass

    def test_code_security_get_repositories_for_enterprise_configuration(self) -> None:
        """Test case for code_security_get_repositories_for_enterprise_configuration

        Get repositories associated with an enterprise code security configuration
        """
        pass

    def test_code_security_get_single_configuration_for_enterprise(self) -> None:
        """Test case for code_security_get_single_configuration_for_enterprise

        Retrieve a code security configuration of an enterprise
        """
        pass

    def test_code_security_set_configuration_as_default(self) -> None:
        """Test case for code_security_set_configuration_as_default

        Set a code security configuration as a default for an organization
        """
        pass

    def test_code_security_set_configuration_as_default_for_enterprise(self) -> None:
        """Test case for code_security_set_configuration_as_default_for_enterprise

        Set a code security configuration as a default for an enterprise
        """
        pass

    def test_code_security_update_configuration(self) -> None:
        """Test case for code_security_update_configuration

        Update a code security configuration
        """
        pass

    def test_code_security_update_enterprise_configuration(self) -> None:
        """Test case for code_security_update_enterprise_configuration

        Update a custom code security configuration for an enterprise
        """
        pass


if __name__ == '__main__':
    unittest.main()
