# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.marketplace_purchase2 import MarketplacePurchase2

class TestMarketplacePurchase2(unittest.TestCase):
    """MarketplacePurchase2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarketplacePurchase2:
        """Test MarketplacePurchase2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarketplacePurchase2`
        """
        model = MarketplacePurchase2()
        if include_optional:
            return MarketplacePurchase2(
                account = github_openapi.models.webhooks_marketplace_purchase_account.webhooks_marketplace_purchase_account(
                    id = 56, 
                    login = '', 
                    node_id = '', 
                    organization_billing_email = '', 
                    type = '', ),
                billing_cycle = '',
                free_trial_ends_on = None,
                next_billing_date = '',
                on_free_trial = True,
                plan = github_openapi.models.webhooks_previous_marketplace_purchase_plan.webhooks_previous_marketplace_purchase_plan(
                    bullets = [
                        ''
                        ], 
                    description = '', 
                    has_free_trial = True, 
                    id = 56, 
                    monthly_price_in_cents = 56, 
                    name = '', 
                    price_model = 'FREE', 
                    unit_name = '', 
                    yearly_price_in_cents = 56, ),
                unit_count = 56
            )
        else:
            return MarketplacePurchase2(
                account = github_openapi.models.webhooks_marketplace_purchase_account.webhooks_marketplace_purchase_account(
                    id = 56, 
                    login = '', 
                    node_id = '', 
                    organization_billing_email = '', 
                    type = '', ),
                billing_cycle = '',
                free_trial_ends_on = None,
                next_billing_date = '',
                on_free_trial = True,
                plan = github_openapi.models.webhooks_previous_marketplace_purchase_plan.webhooks_previous_marketplace_purchase_plan(
                    bullets = [
                        ''
                        ], 
                    description = '', 
                    has_free_trial = True, 
                    id = 56, 
                    monthly_price_in_cents = 56, 
                    name = '', 
                    price_model = 'FREE', 
                    unit_name = '', 
                    yearly_price_in_cents = 56, ),
                unit_count = 56,
        )
        """

    def testMarketplacePurchase2(self):
        """Test MarketplacePurchase2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
