# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.orgs_create_or_update_custom_properties_request import OrgsCreateOrUpdateCustomPropertiesRequest

class TestOrgsCreateOrUpdateCustomPropertiesRequest(unittest.TestCase):
    """OrgsCreateOrUpdateCustomPropertiesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgsCreateOrUpdateCustomPropertiesRequest:
        """Test OrgsCreateOrUpdateCustomPropertiesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgsCreateOrUpdateCustomPropertiesRequest`
        """
        model = OrgsCreateOrUpdateCustomPropertiesRequest()
        if include_optional:
            return OrgsCreateOrUpdateCustomPropertiesRequest(
                properties = [
                    github_openapi.models.organization_custom_property.Organization Custom Property(
                        property_name = '', 
                        url = '', 
                        source_type = 'organization', 
                        value_type = 'single_select', 
                        required = True, 
                        default_value = null, 
                        description = '', 
                        allowed_values = [
                            ''
                            ], 
                        values_editable_by = 'org_actors', )
                    ]
            )
        else:
            return OrgsCreateOrUpdateCustomPropertiesRequest(
                properties = [
                    github_openapi.models.organization_custom_property.Organization Custom Property(
                        property_name = '', 
                        url = '', 
                        source_type = 'organization', 
                        value_type = 'single_select', 
                        required = True, 
                        default_value = null, 
                        description = '', 
                        allowed_values = [
                            ''
                            ], 
                        values_editable_by = 'org_actors', )
                    ],
        )
        """

    def testOrgsCreateOrUpdateCustomPropertiesRequest(self):
        """Test OrgsCreateOrUpdateCustomPropertiesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
