# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.actions_list_self_hosted_runner_groups_for_org200_response import ActionsListSelfHostedRunnerGroupsForOrg200Response

class TestActionsListSelfHostedRunnerGroupsForOrg200Response(unittest.TestCase):
    """ActionsListSelfHostedRunnerGroupsForOrg200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionsListSelfHostedRunnerGroupsForOrg200Response:
        """Test ActionsListSelfHostedRunnerGroupsForOrg200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionsListSelfHostedRunnerGroupsForOrg200Response`
        """
        model = ActionsListSelfHostedRunnerGroupsForOrg200Response()
        if include_optional:
            return ActionsListSelfHostedRunnerGroupsForOrg200Response(
                total_count = 1.337,
                runner_groups = [
                    github_openapi.models.runner_groups_org.runner-groups-org(
                        id = 1.337, 
                        name = '', 
                        visibility = '', 
                        default = True, 
                        selected_repositories_url = '', 
                        runners_url = '', 
                        hosted_runners_url = '', 
                        inherited = True, 
                        inherited_allows_public_repositories = True, 
                        allows_public_repositories = True, 
                        workflow_restrictions_read_only = True, 
                        restricted_to_workflows = True, 
                        selected_workflows = [
                            'octo-org/octo-repo/.github/workflows/deploy.yaml@main'
                            ], )
                    ]
            )
        else:
            return ActionsListSelfHostedRunnerGroupsForOrg200Response(
                total_count = 1.337,
                runner_groups = [
                    github_openapi.models.runner_groups_org.runner-groups-org(
                        id = 1.337, 
                        name = '', 
                        visibility = '', 
                        default = True, 
                        selected_repositories_url = '', 
                        runners_url = '', 
                        hosted_runners_url = '', 
                        inherited = True, 
                        inherited_allows_public_repositories = True, 
                        allows_public_repositories = True, 
                        workflow_restrictions_read_only = True, 
                        restricted_to_workflows = True, 
                        selected_workflows = [
                            'octo-org/octo-repo/.github/workflows/deploy.yaml@main'
                            ], )
                    ],
        )
        """

    def testActionsListSelfHostedRunnerGroupsForOrg200Response(self):
        """Test ActionsListSelfHostedRunnerGroupsForOrg200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
