# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from github_openapi.models.code_security_update_enterprise_configuration_request_dependency_graph_autosubmit_action_options import CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions

class TestCodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions(unittest.TestCase):
    """CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions:
        """Test CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions`
        """
        model = CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions()
        if include_optional:
            return CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions(
                labeled_runners = True
            )
        else:
            return CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions(
        )
        """

    def testCodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions(self):
        """Test CodeSecurityUpdateEnterpriseConfigurationRequestDependencyGraphAutosubmitActionOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
