name: wallabag
services:
  wallabag:
    image: wallabag/wallabag:2.6.10
    restart: unless-stopped
    volumes:
      - ./storage/images:/var/www/wallabag/web/assets/images
      - ./storage/data:/var/www/wallabag/data
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.home.ohmymndy.com
    env_file:
      - .env
    networks:
      - default
      - reverse-proxy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost",
        ]
      interval: 1m
      timeout: 3s
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag.home.ohmymndy.com`)"
      - "traefik.http.routers.wallabag.tls=true"
      - "traefik.enable=true"

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
