name: lldap
x-lldap: &lldap
  image: lldap/lldap:2024-12-24
  restart: unless-stopped
  volumes:
    - "./storage/lldap:/data"
    - ./bootstrap:/bootstrap:ro
  environment:
    - UID=${PUID:?}
    - GID=${PGID:?}
    - TZ=${TIMEZONE:?}
    - LLDAP_JWT_SECRET=${LLDAP_JWT_SECRET:?}
    - LLDAP_KEY_SEED=${LLDAP_KEY_SEED:?}
    - LLDAP_LDAP_BASE_DN=dc=ohmymndy,dc=com
    - LLDAP_LDAP_USER_PASS=${LLDAP_LDAP_USER_PASS:?}
    # If using LDAPS, set enabled true and configure cert and key path
    # - LLDAP_LDAPS_OPTIONS__ENABLED=true
    # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
    # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
    # You can also set a different database:
    # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
    # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
    # If using SMTP, set the following variables
    # - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
    # - LLDAP_SMTP_OPTIONS__SERVER=smtprelay
    # - LLDAP_SMTP_OPTIONS__PORT=25# Check your smtp providor's documentation for this setting
    # - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
    # - LLDAP_SMTP_OPTIONS__USER=no-reply@example.com # The SMTP user, usually your email address
    # - LLDAP_SMTP_OPTIONS__PASSWORD=PasswordGoesHere # The SMTP password
    # - LLDAP_SMTP_OPTIONS__FROM=${LLDAP_FROM:?} # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
    # - LLDAP_SMTP_OPTIONS__TO=admin <admin@example.com> # Same for reply-to, optional.
    - USER_CONFIGS_DIR=/bootstrap/user-configs
    - GROUP_CONFIGS_DIR=/bootstrap/group-configs
    # - USER_SCHEMAS_DIR=/bootstrap/user-schemas
    # - GROUP_SCHEMAS_DIR=/bootstrap/group-schemas
    - LLDAP_VERBOSE=true
services:
  render-templates:
    image: ohmymndy/alpine
    cpus: 0.5
    mem_limit: 256m
    container_name: lldap-render-templates
    restart: no
    volumes:
      - ./:/lldap
      - ../deploy:/deploy:ro
    working_dir: /lldap
    command:
      - -c
      - |
        source /deploy/functions.sh

        set -e

        if [[ ! -f bootstrap/user-configs/admin.json ]]; then
          ADMIN_PASSWORD="$(random_password)"
          ADMIN_EMAIL="admin@email.com"

          export ADMIN_PASSWORD
          export ADMIN_EMAIL

          add_to_env ADMIN_PASSWORD "$$ADMIN_PASSWORD"
          add_to_env ADMIN_EMAIL "$$ADMIN_EMAIL"

          echo "Rendering template:"
          envsubst < bootstrap/user-configs/admin.json.templ > bootstrap/user-configs/admin.json
        fi
    user: ${PUID:?}:${PGID:?}

  # init:
  #   image: hairyhenderson/gomplate:stable
  #   container_name: litellm-init
  #   restart: no
  #   user: ${PUID:?}:${PGID:?}
  #   working_dir: /config
  #   command: -c .=/users.yaml --input-dir /templates --output-dir /config
  #   volumes:
  #     - ./config:/config
  #     - ./users.yaml:/users.yaml:ro
  #     - ./templates:/templates
  #

  # ldapsearch -D "uid=admin,ou=people,dc=ohmymndy,dc=com" -w "$LDAP_PASSWORD" -x -H ldap://127.0.0.1:3890 -b "dc=ohmymndy,dc=com"
  lldap:
    <<: *lldap
    container_name: lldap
    cpus: 0.5
    mem_limit: 256m
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      - "6360:6360"
      # For the web front-end
      # - "17170:17170"
    networks:
      - default
      - reverse-proxy
      - lldap
    # command: server
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.lldap.rule=Host(`lldap.home.ohmymndy.com`)"
      - "traefik.http.services.lldap.loadbalancer.server.port=17170"
      - "traefik.http.routers.lldap.tls=true"
      - "traefik.enable=true"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:17170",
        ]
      interval: 30s
      timeout: 3s
      start_period: 60s
      start_interval: 5s

  lldap-init:
    <<: *lldap
    entrypoint: /bin/bash
    container_name: lldap-init
    cpus: 0.5
    mem_limit: 256m
    restart: no
    command:
      - -c
      - |
        bash /app/bootstrap.sh
    environment:
      - LLDAP_URL=http://lldap:17170
      - LLDAP_ADMIN_PASSWORD=${LLDAP_LDAP_USER_PASS:?}
    depends_on:
      lldap:
        condition: service_healthy
      render-templates:
        condition: service_completed_successfully

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
  lldap:
    name: lldap_default
    external: true
