services:
  smtprelay:
    image: grafana/smtprelay:2.1.5
    container_name: smtprelay
    restart: unless-stopped
    init: true
    command:
      - -remote_host=${REMOTE_HOST:?}
      - -remote_user=${REMOTE_USER:?}
      - -remote_sender=${REMOTE_SENDER:?}
      - -remote_pass=${REMOTE_PASS:?}
      - -allowed_sender=${ALLOWED_SENDER:?}
      - -allowed_recipients=${ALLOWED_RECIPIENTS:-}
      - -hostname=smtprelay
      - -listen=${LISTEN:?}
      - -allowed_nets=${ALLOWED_NETS:-}
    ports:
      - 127.0.0.1:25:25

networks:
  default:
    name: smtprelay
