# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ApiOverviewSshKeyFingerprints(BaseModel):
    """
    ApiOverviewSshKeyFingerprints
    """ # noqa: E501
    sha256_rsa: Optional[StrictStr] = Field(default=None, alias="SHA256_RSA")
    sha256_dsa: Optional[StrictStr] = Field(default=None, alias="SHA256_DSA")
    sha256_ecdsa: Optional[StrictStr] = Field(default=None, alias="SHA256_ECDSA")
    sha256_ed25519: Optional[StrictStr] = Field(default=None, alias="SHA256_ED25519")
    __properties: ClassVar[List[str]] = ["SHA256_RSA", "SHA256_DSA", "SHA256_ECDSA", "SHA256_ED25519"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiOverviewSshKeyFingerprints from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiOverviewSshKeyFingerprints from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "SHA256_RSA": obj.get("SHA256_RSA"),
            "SHA256_DSA": obj.get("SHA256_DSA"),
            "SHA256_ECDSA": obj.get("SHA256_ECDSA"),
            "SHA256_ED25519": obj.get("SHA256_ED25519")
        })
        return _obj


