# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from github_openapi.models.webhook_config_insecure_ssl import WebhookConfigInsecureSsl
from typing import Optional, Set
from typing_extensions import Self

class AppsUpdateWebhookConfigForAppRequest(BaseModel):
    """
    AppsUpdateWebhookConfigForAppRequest
    """ # noqa: E501
    url: Optional[StrictStr] = Field(default=None, description="The URL to which the payloads will be delivered.")
    content_type: Optional[StrictStr] = Field(default=None, description="The media type used to serialize the payloads. Supported values include `json` and `form`. The default is `form`.")
    secret: Optional[StrictStr] = Field(default=None, description="If provided, the `secret` will be used as the `key` to generate the HMAC hex digest value for [delivery signature headers](https://docs.github.com/webhooks/event-payloads/#delivery-headers).")
    insecure_ssl: Optional[WebhookConfigInsecureSsl] = None
    __properties: ClassVar[List[str]] = ["url", "content_type", "secret", "insecure_ssl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AppsUpdateWebhookConfigForAppRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of insecure_ssl
        if self.insecure_ssl:
            _dict['insecure_ssl'] = self.insecure_ssl.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AppsUpdateWebhookConfigForAppRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "content_type": obj.get("content_type"),
            "secret": obj.get("secret"),
            "insecure_ssl": WebhookConfigInsecureSsl.from_dict(obj["insecure_ssl"]) if obj.get("insecure_ssl") is not None else None
        })
        return _obj


