# coding: utf-8

"""
    GitHub v3 REST API

    GitHub's v3 REST API.

    The version of the OpenAPI document: 1.1.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SecretScanningAlertResolutionWebhook(str, Enum):
    """
    The reason for resolving the alert.
    """

    """
    allowed enum values
    """
    FALSE_POSITIVE = 'false_positive'
    WONT_FIX = 'wont_fix'
    REVOKED = 'revoked'
    USED_IN_TESTS = 'used_in_tests'
    PATTERN_DELETED = 'pattern_deleted'
    PATTERN_EDITED = 'pattern_edited'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SecretScanningAlertResolutionWebhook from a JSON string"""
        return cls(json.loads(json_str))


