{
 "title": "Node exporter single server",
 "description": "Dashboard to get an overview of one server",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": {
     "query": "label_values(node_boot_time_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Idle cpu",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} - node_memory_MemFree_bytes{instance=~\"$server\"}",
     "legendFormat": "free memory"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemFree_bytes{instance=~\"$server\"} / node_memory_MemTotal_bytes{instance=~\"$server\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_disk_read_bytes_total{instance=~\"$server\"}[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_write_bytes_total{instance=~\"$server\"}[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum by (instance) (irate(node_disk_io_time_seconds_total{instance=~\"$server\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Free disk space (lowest mountpoint)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device!=\"rootfs\",instance=~\"$server\"} / node_filesystem_size_bytes{device!=\"rootfs\",instance=~\"$server\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Data transfer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$server\",device!~\"^lo|br-.*|veth.*$\"}[5m])",
     "legendFormat": "received {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$server\",device!~\"^lo|br-.*|veth.*$\"}[5m])",
     "legendFormat": "transmitted {{device}}"
    }
   ]
  }
 ]
}