name: openwebui
services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:0.5.4
    volumes:
      - ./storage/open-webui:/app/backend/data
    env_file:
      - .env
    environment:
      # SEE: https://docs.openwebui.com/tutorials/tips/reduce-ram-usage/
      RAG_EMBEDDING_ENGINE: ollama
      AUDIO_STT_ENGINE: openai
    networks:
      - default
      - reverse-proxy
      - lldap
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.openwebui.rule=Host(`openwebui.home.ohmymndy.com`)"
      - "traefik.http.routers.openwebui.tls=true"
      - "traefik.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://127.0.0.1:8080"]
      interval: 15s
      timeout: 2s
      retries: 3
      start_period: 40s
      start_interval: 5s
  pipelines:
    image: ghcr.io/open-webui/pipelines:git-1367d95
    volumes:
      - ./storage/pipelines:/app/pipelines
    networks:
      - default
      - reverse-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.openwebui-pipelines.rule=Host(`openwebui-pipeline\
        s.home.ohmymndy.com`)"
      - "traefik.http.routers.openwebui-pipelines.tls=true"
      - "traefik.enable=true"
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://127.0.0.1:9099"]
      interval: 15s
      timeout: 2s
      retries: 3
      start_period: 40s
      start_interval: 5s

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
  lldap:
    name: lldap_default
    external: true
