litellm_settings:
  json_logs: true
general_settings:
  disable_master_key_return: true
model_list:
  # TODO: https://openrouter.ai/models
  # Paid models


  - model_name: "mistralai/mistral-nemo"
    litellm_params:
      model: "openrouter/mistralai/mistral-nemo"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]
  - model_name: "mistralai/mistral-large-2411"
    litellm_params:
      model: "openrouter/mistralai/mistral-large-2411"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]

  - model_name: "openai/gpt-4o-2024-11-20"
    litellm_params:
      model: "openrouter/openai/gpt-4o-2024-11-20"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]

  - model_name: "google/gemini-2.0-flash-001"
    litellm_params:
      model: "openrouter/mistralai/mistral-large-2411"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]

  - model_name: "google/palm-2-codechat-bison"
    litellm_params:
      model: "openrouter/google/palm-2-codechat-bison"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]

  - model_name: "meta-llama/llama-3.1-8b-instruct"
    litellm_params:
      model: "openrouter/meta-llama/llama-3.1-8b-instruct"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]

  - model_name: "openai/o1-mini-2024-09-12"
    litellm_params:
      model: "openrouter/openai/o1-mini-2024-09-12"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]
  - model_name: "deepseek/deepseek-r1-distill-llama-70b"
    litellm_params:
      model: "openrouter/deepseek/deepseek-r1-distill-llama-70b"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]
  # - model_name: "deepseek/deepseek-r1:free"
  #   litellm_params:
  #     model: "openrouter/deepseek/deepseek-r1:free"
  #     api_key: os.environ/OPENROUTER_API_KEY
  #     tags: ["free"]
  - model_name: "deepseek/deepseek-r1"
    litellm_params:
      model: "openrouter/deepseek/deepseek-r1"
      api_key: os.environ/OPENROUTER_API_KEY
      tags: ["paid"]
  # - model_name: "deepseek/deepseek-chat"
  #   litellm_params:
  #     model: "openrouter/deepseek/deepseek-chat"
  #     api_key: os.environ/OPENROUTER_API_KEY
  #     tags: ["paid"]
  - model_name: "ollama/phi4:14b (self hosted)"
    litellm_params:
      tags: ["free"]
      model: "ollama/phi4:14b"
      api_base: http://ollama.10.0.40.51.sslip.io/
      extra_headers:
      "Authorization": "ollama:password"
