# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.6.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.ldap_property_mapping_request import LDAPPropertyMappingRequest

class TestLDAPPropertyMappingRequest(unittest.TestCase):
    """LDAPPropertyMappingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LDAPPropertyMappingRequest:
        """Test LDAPPropertyMappingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LDAPPropertyMappingRequest`
        """
        model = LDAPPropertyMappingRequest()
        if include_optional:
            return LDAPPropertyMappingRequest(
                managed = '0',
                name = '0',
                expression = '0',
                object_field = '0'
            )
        else:
            return LDAPPropertyMappingRequest(
                name = '0',
                expression = '0',
                object_field = '0',
        )
        """

    def testLDAPPropertyMappingRequest(self):
        """Test LDAPPropertyMappingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
