# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.6.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.digest_algorithm_enum import DigestAlgorithmEnum

class TestDigestAlgorithmEnum(unittest.TestCase):
    """DigestAlgorithmEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDigestAlgorithmEnum(self):
        """Test DigestAlgorithmEnum"""
        # inst = DigestAlgorithmEnum()

if __name__ == '__main__':
    unittest.main()
