# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.6.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.paginated_docker_service_connection_list import PaginatedDockerServiceConnectionList

class TestPaginatedDockerServiceConnectionList(unittest.TestCase):
    """PaginatedDockerServiceConnectionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedDockerServiceConnectionList:
        """Test PaginatedDockerServiceConnectionList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedDockerServiceConnectionList`
        """
        model = PaginatedDockerServiceConnectionList()
        if include_optional:
            return PaginatedDockerServiceConnectionList(
                pagination = authentik_openapi.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_openapi.models.docker_service_connection.DockerServiceConnection(
                        pk = '', 
                        name = '', 
                        local = True, 
                        component = '', 
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        url = '', 
                        tls_verification = '', 
                        tls_authentication = '', )
                    ]
            )
        else:
            return PaginatedDockerServiceConnectionList(
                pagination = authentik_openapi.models.pagination.Pagination(
                    next = 1.337, 
                    previous = 1.337, 
                    count = 1.337, 
                    current = 1.337, 
                    total_pages = 1.337, 
                    start_index = 1.337, 
                    end_index = 1.337, ),
                results = [
                    authentik_openapi.models.docker_service_connection.DockerServiceConnection(
                        pk = '', 
                        name = '', 
                        local = True, 
                        component = '', 
                        verbose_name = '', 
                        verbose_name_plural = '', 
                        meta_model_name = '', 
                        url = '', 
                        tls_verification = '', 
                        tls_authentication = '', )
                    ],
        )
        """

    def testPaginatedDockerServiceConnectionList(self):
        """Test PaginatedDockerServiceConnectionList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
