# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.6.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.type_create import TypeCreate

class TestTypeCreate(unittest.TestCase):
    """TypeCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TypeCreate:
        """Test TypeCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TypeCreate`
        """
        model = TypeCreate()
        if include_optional:
            return TypeCreate(
                name = '',
                description = '',
                component = '',
                model_name = '',
                icon_url = '',
                requires_enterprise = True
            )
        else:
            return TypeCreate(
                name = '',
                description = '',
                component = '',
                model_name = '',
        )
        """

    def testTypeCreate(self):
        """Test TypeCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
