# coding: utf-8

"""
    authentik

    Making authentication simple.

    The version of the OpenAPI document: 2024.6.4
    Contact: hello@goauthentik.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from authentik_openapi.models.not_configured_action_enum import NotConfiguredActionEnum

class TestNotConfiguredActionEnum(unittest.TestCase):
    """NotConfiguredActionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotConfiguredActionEnum(self):
        """Test NotConfiguredActionEnum"""
        # inst = NotConfiguredActionEnum()

if __name__ == '__main__':
    unittest.main()
