name: netbootxyz
services:
  init:
    image: alpine:3.21.0
    volumes:
      - ./storage/config:/config
    command:
      - /bin/ash
      - -c
      - |
        # set -e
        wget https://raw.githubusercontent.com/netbootxyz/netboot.xyz/refs/heads/development/endpoints.yml -O /config/endpoints.yml
    user: ${PUID:?}:${PGID:?}

  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:0.7.3-nbxyz2
    container_name: netbootxyz
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ./storage/config:/config
      - ./storage/assets:/assets #optional
    environment:
      - PUID=${PUID:?}
      - PGID=${PGID:?}
      - TZ=${TIMEZONE:?}
      - MENU_VERSION=2.0.83 #optional
      - TFTPD_OPTS='--tftp-single-port'
      # - PORT_RANGE=30000:30010 #optional
      - SUBFOLDER=/ #optional
      - NGINX_PORT=80 #optional
      - WEB_APP_PORT=3000 #optional
    ports:
      - '0.0.0.0:69:69/udp'
      - '0.0.0.0:3000:3000'
      - '0.0.0.0:8089:80' #optional
    restart: unless-stopped
