name: redmine
services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    volumes:
      - ./storage/postresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER:?}
      - POSTGRESQL_DATABASE=${POSTGRES_DB:?}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD:-?}
    restart: unless-stopped

  redmine:
    image: docker.io/bitnami/redmine:5
    depends_on:
      - postgresql
    volumes:
      - ./storage/redmine:/bitnami/redmine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_TYPE=postgresql
      - REDMINE_DATABASE_HOST=postgresql
      - REDMINE_DATABASE_PORT_NUMBER=5432
      - REDMINE_DATABASE_USER=${POSTGRES_USER:?}
      - REDMINE_DATABASE_PASSWORD=${POSTGRES_PASSWORD:-?}
      - REDMINE_DATABASE_NAME=${POSTGRES_DB:?}
      - REDMINE_REST_API_ENABLED=1
    networks:
      - default
      - reverse-proxy
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.redmine.rule=Host(`redmine.home.ohmymndy.com`)"
      - "traefik.http.routers.redmine.tls=true"
      - "traefik.enable=true"

networks:
  default:
  reverse-proxy:
    external: true
    name: reverse-proxy
