# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: {{AppVer | JSEscape}}
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gitea_openapi.models.create_label_option import CreateLabelOption

class TestCreateLabelOption(unittest.TestCase):
    """CreateLabelOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateLabelOption:
        """Test CreateLabelOption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateLabelOption`
        """
        model = CreateLabelOption()
        if include_optional:
            return CreateLabelOption(
                color = '#00aabb',
                description = '',
                exclusive = False,
                is_archived = False,
                name = ''
            )
        else:
            return CreateLabelOption(
                color = '#00aabb',
                name = '',
        )
        """

    def testCreateLabelOption(self):
        """Test CreateLabelOption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
