---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: reloader
spec:
  interval: 12h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
spec:
  chart:
    spec:
      chart: stakater/reloader
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stakater
      version: v1.3.0
  interval: 1h
  values:
    reloader:
      watchGlobally: true
      autoReloadAll: true
      syncAfterRestart: true
