services:
  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:eb470473
    container_name: tt-rss
    cpus: 0.5
    mem_limit: 256m
    depends_on:
      - db
    volumes:
      - ./storage/app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped

  #  optional, makes weekly backups of your install
  backups:
    image: cthulhoo/ttrss-fpm-pgsql-static:eb470473
    container_name: tt-rss-backups
    cpus: 0.5
    mem_limit: 256m
    depends_on:
      - db
    volumes:
      - ./storage/backups:/backups
      - ./storage/app:/var/www/html
    env_file:
      - .env
    networks:
      - default
    command: /opt/tt-rss/dcron.sh -f
    restart: unless-stopped
    init: true
  db:
    image: postgres:15-alpine
    container_name: tt-rss-postgresql
    cpus: 0.5
    mem_limit: 256m
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    env_file:
      - .env
    networks:
      - default
    restart: unless-stopped
    init: true

  proxy:
    image: nginx:1.27.3
    container_name: tt-rss-proxy
    cpus: 0.25
    mem_limit: 128m
    depends_on:
      - web-nginx
    volumes:
      - ./etc/proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80"
    networks:
      - default
      - reverse-proxy
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.tt-rss.rule=Host(`tt-rss.home.ohmymndy.com`)"
      - "traefik.http.routers.tt-rss.tls=true"
      # - "traefik.http.middlewares.corsheader.headers.accessControlAllowOriginList=*"
      # - "traefik.http.routers.tt-rss.middlewares=corsheader"
      - "traefik.enable=true"
    init: true

  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static:eb470473
    container_name: tt-rss-updater
    cpus: 0.25
    mem_limit: 256m
    depends_on:
      - app
    volumes:
      - ./storage/app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    env_file:
      - .env
    networks:
      - default
    command: /opt/tt-rss/updater.sh
    restart: unless-stopped
    init: true

  web-nginx:
    image: cthulhoo/ttrss-web-nginx:472058e0
    container_name: tt-rss-nginx
    cpus: 0.25
    mem_limit: 128m
    depends_on:
      - app
    volumes:
      - ./storage/app:/var/www/html:ro
    env_file:
      - .env
    restart: unless-stopped
    init: true

networks:
  default:
  reverse-proxy:
    external: true
    name: reverse-proxy
