- name: Install required packages
  apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - containerd
      - bash-completion
      - conntrack # is this necessary for containerd?
    state: present


- name: Create directory for APT keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add kubernetes keyring
  timeout: 5
  shell: |
    set -e
    rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    curl -fsSL "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major_version }}/deb/Release.key" | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  changed_when: false

- name: Add kubernetes repo
  shell: |
    set -e
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_major_version }}/deb/ /" > /etc/apt/sources.list.d/kubernetes.list
  changed_when: false


- name: Install Kubernetes packages
  apt:
    update_cache: true
    name:
      - kubelet={{ kubernetes_major_version }}.{{ kubernetes_minor_version }}-1.1
      - kubeadm={{ kubernetes_major_version }}.{{ kubernetes_minor_version }}-1.1
      - kubectl={{ kubernetes_major_version }}.{{ kubernetes_minor_version }}-1.1
    state: present

- name: Hold Kubernetes packages
  command: apt-mark hold kubelet kubeadm kubectl
  changed_when: false


- name: Configure sysctl for Kubernetes
  copy:
    content: |
      fs.inotify.max_user_watches = 524288
      fs.inotify.max_user_instances = 512
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
    mode: '0644'
  register: sysctl

- name: Apply sysctl settings
  command: sudo sysctl --system
#  changed_when: sysctl.

- name: Check if file exists
  stat:
    path: "/etc/containerd/config.toml"
  register: containerd_config

- name: Configure containerd
  shell: |
    set -eu
    if [ ! -d /etc/containerd ]; then
      mkdir -p /etc/containerd
  
      containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
      sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
      systemctl restart containerd
    fi
