name: adguard
services:
  app:
    image: adguard/adguardhome:v0.107.55
    container_name: adguard
    volumes:
      - ./storage/work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    ports:
      - "${LOCAL_IP}:53:53/tcp"
      - "${LOCAL_IP}:53:53/udp"
      - "${TAILSCALE_IP:?}:53:53/tcp"
      - "${TAILSCALE_IP:?}:53:53/udp"
    entrypoint:
      [
        "ash",
        "-c",
        'set -x; echo $#;  umask 000; exec /opt/adguardhome/AdGuardHome "$@"',
        "--",
      ]

    networks:
      - default
      - reverse-proxy
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home.ohmymndy.com`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      # use port 3000 to set it up first time
      # - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.enable=true"
    init: true
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:3000",
        ]
      interval: 30s
      timeout: 3s

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
