version: "3.8"
services:
  app:
    image: adguard/adguardhome:v0.107.43
    volumes:
    - ./storage/work:/opt/adguardhome/work
    - ./config:/opt/adguardhome/conf

    restart: unless-stopped

    init: true

    networks:
      - default
      - reverse-proxy
    ports:
      - 53:53/tcp
      - 53:53/udp
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home.ohmymndy.com`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      # use port 3000 to set it up first time
      # - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.enable=true"

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true