name: adguard
services:
  app:
    image: adguard/adguardhome:v0.107.54
    volumes:
      - ./storage/work:/opt/adguardhome/work
      - ./config:/opt/adguardhome/conf
    ports:
      - '${LOCAL_IP}:53:53/tcp'
      - '${LOCAL_IP}:53:53/udp'
      - '${TAILSCALE_IP:?}:53:53/tcp'
      - '${TAILSCALE_IP:?}:53:53/udp'
    networks:
      - default
      - reverse-proxy
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.adguard.rule=Host(`adguard.home.ohmymndy.com`)"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"
      # use port 3000 to set it up first time
      # - "traefik.http.services.adguard.loadbalancer.server.port=3000"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.enable=true"
    init: true

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
