services:
  spotweb:
    image: erikdevries/spotweb
    container_name: spotweb
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
      CRON_INTERVAL: "*/1 * * * *"
      DB_PASS: ${MYSQL_PASSWORD:?}
    volumes:
      - ./storage/cache:/app/cache
    cpus: 0.5
    mem_limit: 1g
    networks:
      - default
      - reverse-proxy
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.spotweb.rule=Host(`spotweb.home.ohmymndy.com`)"
      # - "traefik.http.routers.spotweb.service=spotweb"
      # - "traefik.http.services.spotweb.loadbalancer.server.port=80"
      - "traefik.http.routers.spotweb.tls=true"
      - "traefik.enable=true"

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 1024m
    container_name: spotweb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: spotweb
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?}
      MYSQL_DATABASE: spotweb
    volumes:
      - ./storage/mysql:/var/lib/mysql

  nzbget:
    image: nzbgetcom/nzbget:v24.8
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
      - NZBGET_USER=${NZBGET_USER:?} #optional
      - NZBGET_PASS=${NZBGET_PASS:?}
    volumes:
      - ./nzbget:/config
      # - ~/Downloads/nzbget:/downloads #optional
      - /mnt/media/downloads/nzbget:/downloads #optional
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 256m
    networks:
      - default
      - reverse-proxy
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.home.ohmymndy.com`)"
      # - "traefik.http.routers.spotweb.service=spotweb"
      # - "traefik.http.services.spotweb.loadbalancer.server.port=80"
      - "traefik.http.routers.nzbget.tls=true"
      - "traefik.enable=true"
volumes:
  dbdata:

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
  lldap:
    name: lldap_default
    external: true
