scrape_configs:
  - job_name: "nodeexporter"
    scrape_interval: 10s
    static_configs:
      - targets: ["nodeexporter:9100"]

  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]
