repositories:
  - name: stakater
    url: https://stakater.github.io/stakater-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: longhorn
    url: https://charts.longhorn.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: cilium
    url: https://helm.cilium.io/
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard/
  - name: incubator
    url: https://charts.helm.sh/incubator
  - name: rancher-latest
    url: https://releases.rancher.com/server-charts/latest
  - name: suse-edge
    url: https://suse-edge.github.io/charts
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts
  - name: flagger
    url: https://flagger.app
  - name: rook-release
    url: https://charts.rook.io/release
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  # - name: prometheus-operator-crds
  #   chart: prometheus-community/prometheus-operator-crds
  #   version: 17.0.2
  #   wait: true
  #   timeout: 30
  - name: metallb
    chart: metallb/metallb
    namespace: metallb
    version: 0.14.9
    wait: true
    timeout: 120
    # values:

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    namespace: ingress-nginx
    version: 4.12.0
    wait: true
    timeout: 60

  - name: prometheus
    chart: prometheus-community/kube-prometheus-stack
    namespace: prometheus
    version: 69.1.0
    wait: true
    timeout: 300
    values:
      - alertmanager:
          ingress:
            enabled: true
            hosts:
              - alertmanager.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
      - grafana:
          ingress:
            enabled: true
            hosts:
              - grafana.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
      - prometheus:
          # networkPolicy:
          #   enabled: true
          #   flavor: cilium
          ingress:
            enabled: true
            hosts:
              - prometheus.{{ requiredEnv "IP_ADDRESS" }}.sslip.io

  - name: flagger
    chart: flagger/flagger
    namespace: ingress-nginx
    needs:
      - ingress-nginx/ingress-nginx
    version: v1.40.0
    wait: true
    timeout: 120
    values:
      - prometheus:
          install: true
      - meshProvider: nginx

  - name: reloader
    namespace: reloader
    chart: stakater/reloader
    version: v1.2.1
    wait: true
    timeout: 180
    # needs:
    #   - kube-system/cilium
    values:
      - reloader:
          watchGlobally: true
          autoReloadAll: true
          reloadOnCreate: true
          syncAfterRestart: true
          reloadStrategy: annotations

  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: v1.16.2
    wait: true
    timeout: 300
    # needs:
    #   - kube-system/cilium
    values:
      - crds:
          enabled: true
      - prometheus:
          enabled: true

  - name: cert-manager-issuers
    chart: incubator/raw
    version: 0.1.0
    wait: true
    timeout: 30
    needs:
      - cert-manager/cert-manager
    values:
      - resources:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: selfsigned
            spec:
              selfSigned: {}

  - name: rancher
    namespace: cattle-system
    chart: rancher-latest/rancher
    version: v2.10.1
    wait: true
    timeout: 600
    needs:
      - cert-manager/cert-manager
    values:
      - hostname: rancher.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
      - replicas: 1

  - name: kubevirt-dashboard-extension
    namespace: cattle-ui-plugin-system
    chart: suse-edge/kubevirt-dashboard-extension
    version: 1.2.1
    wait: true
    timeout: 180
    needs:
      - cattle-system/rancher
    # values:
    #   - hostname: rancher.{{ requiredEnv "IP_ADDRESS" }}.sslip.io
    #   - replicas: 1
