name: nfty
services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    command:
      - serve
    environment:
      - TZ=${TIMEZONE:?}
    user: ${PUID:?}:${PGID:?}
    volumes:
      - ./storage/ntfy:/var/cache/ntfy
      - ./ntfy:/etc/ntfy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - default
      - reverse-proxy
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.nfty.rule=Host(`nfty.home.ohmymndy.com`)"
      - "traefik.http.routers.nfty.tls=true"
      - "traefik.enable=true"

networks:
  default:
  reverse-proxy:
    external: true
    name: reverse-proxy
