#!/bin/sh
set -e
usermod -u $UID 2>/dev/null | echo
groupmod -g $GID 2>/dev/null | echo
# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
