name: portainer
services:
  portainer:
    image: portainer/portainer-ce:2.25.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./storage/portainer:/data
    networks:
      - default
      - reverse-proxy
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.portainer.rule=Host(`portainer.home.ohmymndy.com`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.enable=true"

networks:
  default:
  reverse-proxy:
    external: true
    name: reverse-proxy
