apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: victoriametrics-datasource
    access: proxy
    url: http://victoriametrics:8428
    uid: victoriametrics-1
    # see https://grafana.com/docs/grafana/latest/administration/provisioning/#json-data
    jsonData:
      # vmuiUrl will auto resolve into http://victoriametrics:8428 and won't work at user's machine
      # so we override it
      vmuiUrl: http://localhost:8428/vmui
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: true
    uid: prometheus-1
    url: http://victoriametrics:8428
    # see https://grafana.com/docs/grafana/latest/administration/provisioning/#json-data
    jsonData:
      # vmuiUrl will auto resolve into http://victoriametrics:8428 and won't work at user's machine
      # so we override it
      vmuiUrl: http://localhost:8428/vmui
