name: minio
services:
  minio-init:
    image: minio/mc:RELEASE.2025-02-08T19-14-21Z
    container_name: minio-init
    init: true
    restart: no
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: |
      bash -c "
        mc config host add minio http://minio:9000 ${MINIO_ROOT_USER:?} "${MINIO_ROOT_PASSWORD:?}"
        mc mb -p minio/homelab/tfstate
        
        mc admin user add myminio ${MINIO_TERRAFORM_USER:?} "${MINIO_TERRAFORM_PASSWORD:?}"
        
        tail -f /dev/null &
        wait $!
      " 
      
  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z
    container_name: minio
    init: true
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:?}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?}
      - MINIO_BROWSER_REDIRECT_URL=https://minio-console.home.ohmymndy.com
    volumes:
      - ./storage/minio:/data
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      - default
      - reverse-proxy
    restart: unless-stopped
    labels:
      - "traefik.docker.network=reverse-proxy"

      - "traefik.http.routers.minio-api.rule=Host(`minio-api.home.ohmymndy.com`)"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-api.tls=true"


      - "traefik.http.routers.minio-console.rule=Host(`minio-console.home.ohmymndy.com`)"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-console.tls=true"

      - "traefik.enable=true"
    healthcheck:
      test:
        ["CMD-SHELL", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/9001"]
      interval: 1m
      timeout: 1s
      retries: 3
      start_period: 30s
      start_interval: 1s

networks:
  default:
  reverse-proxy:
    name: reverse-proxy
    external: true
