services:
  tetragon:
    image: quay.io/cilium/tetragon:v1.2.0
    privileged: true
    pid: "host"
    cgroup: "host"
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      # - ./tetragon.tp.d:/etc/tetragon/tetragon.tp.d:ro
      - /sys/kernel/btf/vmlinux:/var/lib/tetragon/btf:ro
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none

networks:
  default:
    external: true
    name: host
