# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services
- My First Group:
  - My First Service:
    href: http://localhost/
    description: Homepage is awesome
- My Second Group:
  - My Second Service:
      href: http://localhost/
      description: Homepage is the best
- My Third Group:
  - Traefik:
      href: https://traefik.home.ohmymndy.com
      widget:
         type: traefik
         url: http://traefik:8080
         # username: username # optional
         # password: password # optional
